### PR TITLE
fixes for building projects without pyproject.toml files

### LINKED ISSUE #9: Jinja2 does not have a pyproject.toml
Jinja2 does not have a pyproject.toml, which means the script to extract the dependencies reports none, even though it has some. That then leads to build failures later when the dependency isn't present in the local server.

The build error I see:

```
Processing ./Jinja2-3.1.3.tar.gz
  Created temporary directory: /tmp/pip-req-build-6amjpr6t
  File was already downloaded /home/dhellmann/devel/rebuilding-the-wheel/wheelbuild6Qyv/Jinja2-3.1.3.tar.gz
  Added file:///home/dhellmann/devel/rebuilding-the-wheel/wheelbuild6Qyv/Jinja2-3.1.3.tar.gz to build tracker '/tmp/pip-build-tracker-etqpfktk'
  Created temporary directory: /tmp/pip-build-env-ugtj8ohu
  Installing build dependencies: started
  Running command pip subprocess to install build dependencies
  Using pip 24.0 from /home/dhellmann/devel/rebuilding-the-wheel/venvOwio/lib/python3.9/site-packages/pip (python 3.9)
  Looking in indexes: http://localhost:8000/simple
127.0.0.1 - - [21/Mar/2024 09:18:19] code 404, message File not found
127.0.0.1 - - [21/Mar/2024 09:18:19] "GET /simple/setuptools/ HTTP/1.1" 404 -
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.
  full command: /home/dhellmann/devel/rebuilding-the-wheel/venvOwio/bin/python3.9 /home/dhellmann/devel/rebuilding-the-wheel/venvOwio/lib/python3.9/site-packages/pip/__pip-runner__.py install --ignore-installed --no-user --prefix /tmp/pip-build-env-ugtj8ohu/overlay --no-warn-script-location -v --no-binary :none: --only-binary :none: -i http://localhost:8000/simple -- 'setuptools>=40.8.0'
  cwd: [inherit]
  Installing build dependencies: finished with status 'error'
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

### PR DESCRIPTION
**Pull request by dhellmann**
* cope with projects that have no pyproject.toml at all
* handle all requirements, regardless of whether there is a marker

Fixes #9

### CODE REVIEW

File: mirror-sdists.sh [hunk 1]
```diff
@@ -16,7 +16,7 @@ TOPLEVEL="${1:-langchain}"
 
 VENV=$TMP/venv
 #VENV=venv
-PYTHON=python3
+PYTHON=python3.9
```
Comment (markmc) [inline mirror-sdists.sh:19]: Mistake?

File: mirror-sdists.sh [hunk 2]
```diff
@@ -62,19 +62,20 @@ collect_build_requires() {
...
-    local pyproject_toml=$(ls -1 $tmp_unpack_dir/*/pyproject.toml)
-    local extract_script=$(pwd)/extract-requires.py
-    local parse_script=$(pwd)/parse_dep.py
+  local extract_script=$(pwd)/extract-requires.py
+  local parse_script=$(pwd)/parse_dep.py
 
-    echo "Processing ${sdist} with pyproject.toml:"
-    cat "${pyproject_toml}"
+  echo "Build system dependencies for ${sdist}:"
+  (cd ${extract_dir} && $PYTHON $extract_script --build-system)
```
Comment (markmc) [inline mirror-sdists.sh:73]: Definitely good idea to output this stuff for debugging

But how about copying your `download_output` trick from below rather than re-running the same script? i.e. capture the output here and then use that for the loop

**Comment by dhellmann** [comment]
Running this branch with top-level set to 'langchain' results in 70 wheels being built successfully, including the one for langchain.

**Comment by markmc** [comment]
> Running this branch on Fedora and Python 3.9 with top-level set to 'langchain' results in 70 wheels being built successfully, including the one for langchain.

Awesome :+1:

File: mirror-sdists.sh (hunk 2 above)
Comment (dhellmann) [reply mirror-sdists.sh:70]: Good point, I'm looking at fixing this now.

**Comment by markmc** [comment]
Thanks!
